@startuml
!include <C4/C4_Container>

skinparam Linetype polyline
skinparam wrapWidth 900

Person(manager, "Менеджер")
Person(client, "Представитель клиента")
Person(user, "Пользователь")

System_Boundary(restaurant_system, "Система Роботизированного Ресторана") {
    ContainerQueue(api, "API Gateway", "Spring Cloud Gateway", "Обработка всех входящих запросов и маршрутизация к соответствующим микросервисам")

    Container(webUI, "Web Application", "Angular", "Веб-приложение для доступа к функционалу системы")
    Container(mobileApp, "Mobile App", "React Native", "Мобильное приложение для управления заказами и взаимодействия с роботами")

    Boundary(registrationBoundary, "Микросервис Регистрации") {
        Container(registrationService, "Регистрационный сервис", "Node.js, Express", "Обработка регистраций пользователей и клиентов")
        ContainerDb(registrationDb, "База данных регистраций", "MongoDB", "Хранение данных пользователей и клиентов")
    }

    Boundary(orderBoundary, "Микросервис Заказов") {
        Container(orderService, "Сервис Заказов", "Java, Spring Boot", "Управление заказами в ресторане")
        ContainerDb(orderDb, "База данных заказов", "MySQL", "Хранение информации о заказах")
    }

    Boundary(paymentBoundary, "Микросервис Оплаты") {
        Container(paymentService, "Сервис Оплаты", "Python, Flask", "Обработка транзакций оплаты")
        ContainerDb(paymentDb, "База данных оплат", "PostgreSQL", "Хранение данных транзакций")
    }

    Boundary(robotBoundary, "Микросервис Управления Роботами") {
        Container(robotService, "Сервис Управления Роботами", "C#, .NET Core", "Координация и мониторинг действий роботов в ресторане")
        ContainerDb(robotDb, "База данных роботов", "SQLite", "Хранение состояний и параметров роботов")
    }
}

Rel_D(user, mobileApp, "Использует")
Rel_D(user, webUI, "Использует")
Rel_D(manager, webUI, "Использует")
Rel_D(client, webUI, "Использует")

Rel_U(api, registrationService, "Маршрутизация запросов")
Rel_U(api, orderService, "Маршрутизация запросов")
Rel_U(api, paymentService, "Маршрутизация запросов")
Rel_U(api, robotService, "Маршрутизация запросов")

Rel_D(webUI, api, "HTTP/HTTPS вызовы")
Rel_D(mobileApp, api, "HTTP/HTTPS вызовы")

Rel_D(registrationService, registrationDb, "Чтение/Запись")
Rel_D(orderService, orderDb, "Чтение/Запись")
Rel_D(paymentService, paymentDb, "Чтение/Запись")
Rel_D(robotService, robotDb, "Чтение/Запись")

@enduml
