# Project information
site_name: Проектирование информационной системы для сети роботизированных ресторанов "Робот и точка"

# Repository
repo_name: mariashapoval/Otus
repo_url: https://github.com/mariashapoval/Otus
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
   - swagger-ui-tag
   - mermaid2
   - build_plantuml:
     render: 'server' # or "local" for local rendering
     bin_path: '/usr/local/bin/plantuml' # ignored when render: server
     server: 'http://www.plantuml.com/plantuml' # official plantuml server
     disable_ssl_certificate_validation: true # for self-signed and invalid certs
     output_format: 'svg' # or "png"
     diagram_root: 'docs/diagrams' # should reside under docs_dir
     output_folder: 'out'
     input_folder: 'src'
     input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - enumerate-headings:
     exclude:
       - index.md
       - glossary.md
  - glightbox
