# Project information
site_name: Проектирование информационной системы для сети роботизированных ресторанов "Робот и точка"

# Repository
repo_name: mariashapoval/Otus
repo_url: https://github.com/mariashapoval/Otus

theme:
  name: material
  features:
    - navigation.instant # Мгновенная загрузка
    - navigation.tracking # Когда отслеживание привязки включено, URL-адрес в адресной строке автоматически обновляется активным привязкой, как выделено в оглавлении. 
    - navigation.expand # Автоматическое открытие подразделов на панели слева
    - navigation.path # Над заголовком каждой страницы отображается путь
    - navigation.top # Кнопка «назад-вверх»
    - navigation.footer # Переключение кнопками предыдущей/следующей страницы в футере
    - navigation.tabs # Навигационные вкладки
    # - navigation.sections # Отображение верхних вкладок на панели слева
    - navigation.indexes # Скрыть дублирование заголовка на панели слева.
    - toc.integrate # Интеграция подразделов в панель слева
    - toc.follow # Автоматическая прокрутка боковой панели при прокрутке
    - search.highlight # Подсветка вхождений в тексте
    - search.suggest # Автозавершение поискового запроса
    - content.code.copy # Кнопка копирования кода
  language: ru
  palette:
    - scheme: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: pink
      accent: white
    - scheme: violet
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: violet
      accent: lavender

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid

nav:
  - Домашняя страница:
    - index.md
  - Документация:
    - glossary.md
    - architecture.md
    - api.md
