---
@startuml
left to right direction
' skinparam Linetype ortho

actor "Посетитель" as ul
actor "Менеджер по ассортименту" as manager
actor "Менеджер по гостеприимству" as hosp

rectangle "RobotandDot" {
    ' Посетитель
    usecase (UC1: Регистрация пользователя) as UC1
    usecase (UC21: Отмена регистрации клиента) as UC21
    usecase (UC2: Вход в систему) as UC2
    usecase (UC3: Просмотр меню через терминал) as UC3
    usecase (UC4: Интерактивный выбор и добавление блюд в корзину) as UC4
    usecase (UC5: Оформление заказа через терминал) as UC5
    usecase (UC7: Обратная связь и рейтинг блюд) as UC7
    usecase (UC8: Уведомления и акции) as UC8
    usecase (UC9: Бронирование столов через терминал) as UC9
    usecase (UC10: Персонализированные рекомендации на основе предпочтений) as UC10
    usecase (UC22: Изменение информации о столиках) as UC22
usecase (UC23: Оплата заказа) as UC23
usecase (UC24: Выбор способа оплаты) as UC24
usecase (UC25: Аутентификация клиента) as UC25



    ' Менеджер по гостеприимству
    usecase (UC12: Мониторинг активности терминалов) as UC12
    usecase (UC17: Оформление отказов и возвратов) as UC17
    usecase (UC18: Управление бронированием столов) as UC18
    usecase (UC19: Поддержка и решение проблем посетителей) as UC19
    usecase (UC20: Управление обратной связью и отзывами клиентов) as UC20

    ' Менеджер по ассортименту
    usecase (UC11: Обновление меню в реальном времени) as UC11
    usecase (UC13: Конфигурация настроек терминала) as UC13
    usecase (UC14: Управление акциями и специальными предложениями) as UC14
    usecase (UC15: Управление технологическими картами и рецептурами) as UC15
    usecase (UC16: Настройка комплексных предложений и комбо-товаров) as UC16
}

ul -- UC2
ul -- UC3
ul -- UC9
ul – UC23

UC2<.. UC1 : extend
UC2 <.. UC25 : include
UC1 <.. UC21 : extend
UC3 <.. UC4 : include
UC3 <.. UC5 : extend
UC3 <.. UC7 : extend
UC3 <.. UC8 : extend
UC3 <.. UC10 : extend
UC9 <.. UC22 : extend
UC23 <.. UC24: include

hosp -- UC12
hosp -- UC19

UC19 <.. UC17 : extend
UC19 <.. UC18 : extend
UC19 <.. UC20 : extend

manager -- UC14
manager -- UC15

UC14 <.. UC16 : extend
UC14 <.. UC11 : extend
UC14 <.. UC13 : include

@enduml
---
